### ISSUE TITLE
NoAuthorizationCodeError when accessing the app from Facebook

### ISSUE THREAD

**Issue by woniesong92** [mkdynamic/omniauth-facebook#110]
OmniAuth::Strategies::Facebook::NoAuthorizationCodeError

must pass either a code parameter or a signed request (via signed_request parameter or a fbsr_XXX cookie)

This error occurs with the latest version of omniauth.
1. omniauth-facebook-1.4.1
2. omniauth-oauth2-1.1.1
3. omniauth-1.1.3

There are closed issues like #65 and #87 but it seems the source of problem is different now since my site URL is correctly set to http://example.com

omniauth.rb:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET'], :scope => 'email', :provider_ignores_state => true
end
```

Initialization:

```javascript
    window.fbAsyncInit = function() {
      FB.init({
        appId      : <%= ENV['FACEBOOK_KEY'] %>, // App ID
        status     : true, // check login status
        cookie     : true, // enable cookies to allow the server to access the session
        xfbml      : true  // parse XFBML
      });
    };

    // Load the SDK Asynchronously
    (function(d){
       var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement('script'); js.id = id; js.async = true;
       js.src = "//connect.facebook.net/en_US/all.js";
       ref.parentNode.insertBefore(js, ref);
     }(document));
```

And I use the client-side authorization with server-side authorization.

view
```javascript
function login() {
  FB.login(function(response) {
    if (response.authResponse) {
      window.location = '/auth/facebook/callback'
    } 
  }, {scope: 'email,publish_stream,publish_actions'});
}
```

routes
```
  match 'auth/:provider/callback', to: 'sessions#create_facebook'
  match 'auth/failure', to: redirect('/')
```

This error only occurs when I try to sign in
**Inside Facebook, using Internet Explorer.** Chrome, Firefox do not have any problem, and even Internet Explorer is fine if I access the app from outside Facebook.
There is still an open discussion at #56 with the same error, but I'm not sure if that's the same problem as this one.

**Comment by balexand** [comment]
I was having this problem in my development environment. Using the Chrome DevTools, it was clear that the cookie was not being passed with the request to `/auth/facebook/callback`.

After much frustration, I tried creating a new Facebook test app with all of the same settings as the app I'd been using previously. For some reason that made it work.

**Comment by mkdynamic** [comment]
@balexand Odd.

Should note that passing the signed request manually as per https://github.com/mkdynamic/omniauth-facebook/issues/110#issuecomment-27426415 is no longer supported since https://github.com/mkdynamic/omniauth-facebook/commit/765ed9a96752546077f902bee5d43740b4b11b6a#diff-999bca448145eb14d3025d6b5dff0048L153.

**Comment by sistrall** [comment]
I had this error too, while I was migrating from the server side to the client side login flow. I tried many things and finally got my app working again using a "real" domain instead of working on localhost. While using `http://localhost:3000/` no cookie was saved, while everything started working as expected when working with `http://app.lvh.me:3000/` (`lvh.me` and all its subdomain always resolve to 127.0.0.1).

**Comment by frasermince** [comment]
Has anyone managed to figure out what's going on here? I'm struggling with this same issue and can't figure out why it won't work.

**Comment by urbanvikingr** [comment]
+1

**Comment by aug-riedinger** [comment]
:+1:

**Comment by joaomilho** [comment]
+1

**Comment by dydx** [comment]
Following this (http://www.sitepoint.com/polling-users-rails/), I get this error:

```
I, [2015-10-05T02:12:07.109459 #15670]  INFO -- omniauth: (facebook) Callback phase initiated.
E, [2015-10-05T02:12:07.110950 #15670] ERROR -- omniauth: (facebook) Authentication failure! no_authorization_code: OmniAuth::Strategies::Facebook::NoAuthorizationCodeError, must pass either a `code` (via URL or by an `fbsr_XXX` signed request cookie)

```

**Comment by urbanvikingr** [comment]
Anybody seen this error?
`{"error":{"message":"Invalid verification code format.","type":"OAuthException","code":100,"fbtrace_id":"Fx6\/Dg4zcKE"}}`

I succeed to pass the signed request from JavaScript client on localhost:8080 to Rails API on localhost:3000 using Facebook's client-side login flow. The url is `http://localhost:3000/api/auth/facebook/callback?code=response.authResponse.signedRequest`.

I'm using jQuery to set url params
`http://localhost:3000/api/auth/facebook/callback? + $.param({ code: response.authResponse.signedRequest });`

Now, I am getting the error mentioned above. It is returned from Facebook upon the Omniauth call, if I'm reading the Omniauth documentation correctly. 

```
How it Works

The client-side flow is supported by parsing the authorization code from the signed request which Facebook places in a cookie.

When you call /auth/facebook/callback in the success callback of FB.login that will pass the cookie back to the server. omniauth-facebook will see this cookie and:

parse it,
extract the authorization code contained in it
and hit Facebook and obtain an access token which will get placed in the request.env['omniauth.auth']['credentials'] hash.
```

**Comment by mkdynamic** [comment]
I think this ticket is covering a multitude of issues, possibly unrelated. Please make sure you're running rh latest omniauth-facebook and omniauth-oauth2 versions. And you need to make sure that either the cookie (containing the signed request) set by FB JS SDK or the signed_request parameter needs to make it to the /auth/facebook/callback request.

Please open separate issues if problems persist.
