### ISSUE TITLE
Popup authentication does not return omniauth.auth

### ISSUE THREAD

**Issue by nguyenannguyen** [mkdynamic/omniauth-facebook#111]
I have omniauth-factbook implemented correctly with Devise. However, I got an error when implementing the authentication in the popup window. I followed Ryan's RailsCast and add display => 'popup' to my provider configuration in omniauth.rb

I successfully login to facebook in the popup window and received a hash request.authRequest from Facebook API, which contained userId.

However, when I got to callback path (/auth/facebook/callback), I didn't get :provider and :uid from request.evn[omniauth.auth] like I used to.

Why omniauth hash was not created even when Facebook API returned the authentication hash? What can I do to fix this issue?

My controller to handle facebook callback is simple:

    class ServicesController < ApplicationController
        def create
        auth = request.env["omniauth.auth"]
       debugger

Right at the debugger, when I use IRB to check, there's no omniauth hash in request.env.

BTW, I think I turned the cookie on in my coffeescript file:

    jQuery ->
        $('body').prepend('<div id="fb-root"></div>')

        $.ajax
        url: "#{window.location.protocol}//connect.facebook.net/en_US/all.js"
        dataType: 'script'
       cache: true

    window.fbAsyncInit = ->
        FB.init(appId: '<%= "myAppID" %>', cookie: true)

    $('#facebook_signin').click (e) ->
        e.preventDefault()
        FB.login (response) ->
            window.location = '/auth/facebook/callback' if response.authResponse

    $('#facebook_signout').click (e) ->
          FB.getLoginStatus (response) ->
          FB.logout() if response.authResponse
          true

Thank you.

**Comment by firetix** [comment]
getting the same issue

**Comment by dixalex** [comment]
Guys, any luck on this? Maybe you know better solution except omniauth?

**Comment by simi** [comment]
Can you try to update https://github.com/mkdynamic/omniauth-facebook/tree/master/example to reproduce your issue?

**Comment by dixalex** [comment]
It works, thank you!
I figured out that that was a mistake in my code.
