### ISSUE TITLE
How parsing the Signed Request in the deauthorize callback?

### ISSUE THREAD

**Issue by Vrael** [mkdynamic/omniauth-facebook#177]
When an user removes a facebook app, a deauthorize callback is called: [Detecting when people uninstall apps](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/v2.2#deauth-callback). I have been looking for if OminiAuth cover this scenary but I have not clear at all. When Facebook hits this url you have to parsing a signed request and I have seen that in OmniAuth exists a method called [parse_signed_request](https://github.com/mkdynamic/omniauth-facebook/blob/f37f24b49f213f9f0d22c6c37bd43a045d093e0d/lib/omniauth/strategies/facebook.rb#LC163) but I am not sure how I should call to this method.

```ruby
on post do
    on 'auth/facebook/deauthorized', param(:signed_request) do |signed_request|
        # How should use that method here?
    end
end
```

Or exist other better way to to do this covered by flow-server in OmniAuth?

**Comment by simi** [comment]
Hello @Vrael. There is [parsed_signed_request](https://github.com/mkdynamic/omniauth-facebook/blob/master/lib/omniauth/strategies/facebook.rb#L163-L177) method, but it is in private scope. It is planned to extract this into `OmniAuth::Facebook::Utils` module and include it in `OmniAuth::Strategies::Facebook`.

You'll be able to call `OmniAuth::Facebook::Utils.parsed_signed_request` directly from your code.

Do you want to prepare PR for this? Should be easy enough IMHO.

**Comment by simi** [comment]
done in #183
