### ISSUE TITLE
Facebook Canvas App

### ISSUE THREAD

**Issue by motro** [mkdynamic/omniauth-facebook#184]
Hi,

Does anyone has a good example on how to use omniauth for a Facebook canvas app?
And keep it in the iframe after successfully authorizing?

Thanks!

**Comment by simi** [comment]
Take a look at example https://github.com/mkdynamic/omniauth-facebook/blob/master/example/app.rb#L24 and removed canvas app example https://github.com/mkdynamic/omniauth-facebook/commit/4f6e40614f0377186b7e6818acfd4048dbc90303.
