### ISSUE TITLE
nickname field removed from facebook

### ISSUE THREAD

**Issue by abelorian** [mkdynamic/omniauth-facebook#185]
The nickname field had been removed from facebook API

Oficial Docs: https://developers.facebook.com/docs/apps/upgrading#upgrading_v2_0_user_ids

**Comment by simi** [comment]
What we need to do? Just remove it from omniauth hash? What about to add username there also?

**Comment by abelorian** [comment]
Adding a #comment in *Auth Hash* section on README.md, maybe
     :info =>     :nickname => 'jbloggs', #Removed in GraphApi 2.0

**Comment by mkdynamic** [comment]
This is not a bug, but PRs with README update are welcome.
