### ISSUE TITLE
How would a user know what their password is when they sign up via facebook?

### ISSUE THREAD

**Issue by GildedHonour** [mkdynamic/omniauth-facebook#193]
When a user signs up via facebook, how would they know what their new, auto-generated password is?

**Comment by simi** [comment]
sorry, but this is not issue

*the trick is they don't need password since they will be signed in via facebook everytime*

**Comment by GildedHonour** [comment]
I agree, it's not, when else could I put it?
I see. I thought a user could also want to login via email/password using their facebook email after they register via facebook previously.

**Comment by simi** [comment]
I used once scenario where user was registered by email and password first and after that he could connect to multiple services (like facebook via omniauth-facebook) to provide data for application.
