### ISSUE TITLE
request email permission again after the user declined it 

### ISSUE THREAD

**Issue by gaaady** [mkdynamic/omniauth-facebook#194]
A user tries to sign up to a website that requires email but checks off the permission.
how do I display the log in dialog again ?

**Comment by simi** [comment]
The best practice is to ask user for email manually in your APP when 3rd party OAuth service is not providing one.

**Comment by simi** [comment]
also see https://developers.facebook.com/docs/facebook-login/login-flow-for-web/v2.3#re-asking-declined-permissions

**Comment by simi** [comment]
And also from readme:
https://github.com/mkdynamic/omniauth-facebook#configuring
https://github.com/mkdynamic/omniauth-facebook#per-request-options

#=> use `/auth/facebook?auth_type=reauthenticate` URL to reask for permission

**Comment by zerocool4u2** [comment]
:facebook, ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_SECRET'], auth_type: 'rerequest'

auth_type works for me, if they decline some permission it will request on each login until they accepts the permissions
