### ISSUE TITLE
Incompatible with response type for v2.3 of Facebook API

### ISSUE THREAD

**Issue by prognostikos** [mkdynamic/omniauth-facebook#196]
The token_params response for version 2.3 of the API is sent as `application/json` whereas omniauth-facebook tries to [parse it as a query string](https://github.com/mkdynamic/omniauth-facebook/blob/c3d2736896a27fa9d4111988b3b048bf79cfd4b6/lib/omniauth/strategies/facebook.rb#L20-L22).

Downgrading to using v2.2 of the API is a workaround.

**Comment by simi** [comment]
@kenn @semaperepelitsa time to solve #190.

**Comment by romanbsd** [comment]
Maybe it's better to bump the gem version and support only API v2.3 or greater?

**Comment by gshaw** [comment]
Thanks for posting a workaround @prognostikos 

For others that get on to this page from Google here is a workable `config/initializer/omniauth.rb` file that does the trick.

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook,
    Rails.application.secrets.facebook_app_id,
    Rails.application.secrets.facebook_app_secret,
    client_options: {
      # OmniAuth not compatible with v2.3+ API so force known working version v2.2
      # https://github.com/mkdynamic/omniauth-facebook/issues/196
      site: "https://graph.facebook.com/v2.2",
      authorize_url: "https://www.facebook.com/v2.2/dialog/oauth"
    },
    setup: true
end
```

**Comment by agrobbin** [comment]
Another option here, for those who want to use `v2.3` or `v2.4` of the API, is to change the `token_params` to parse the access token response as JSON.

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook,
    Rails.application.secrets.omniauth[:facebook][:key],
    Rails.application.secrets.omniauth[:facebook][:secret],
    client_options: {
      site: "https://graph.facebook.com/v2.4",
      authorize_url: "https://www.facebook.com/v2.4/dialog/oauth"
    },
    token_params: {
      parse: :json
    }
end
```

**Comment by grouptable** [comment]
Could we put such initializer when using devise for authentication? The Wiki says: "This means you should not add this provider middleware again in config/initializers/omniauth.rb as they'll clash with each other ..." here: https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview

Could somebody please clarify?

**Comment by gshaw** [comment]
The snippet in @agrobbin above is exactly what I have in my `config/initializer/omniauth.rb` and it works without conflict.  Does that help?

**Comment by grouptable** [comment]
Thank you for the clarification. We will try this today.

**Comment by skryshi** [comment]
Thank you, @agrobbin, your solution worked perfectly.

I also use Devise and init Facebook provider there, so instead of modifying `config/initializer/omniauth.rb`, I added `token_params` directly in `config/initializer/devise.rb`:
```
  config.omniauth :facebook,
    Rails.application.config.facebook.id,
    Rails.application.config.facebook.secret,
    :scope => Rails.application.config.facebook.permissions,
    :display => "page",
    :client_options => {
      :site => "https://graph.facebook.com/" + Rails.application.config.facebook.api_version,
      :authorize_url => "https://www.facebook.com/" + Rails.application.config.facebook.api_version + "/dialog/oauth",
    },
    # https://github.com/mkdynamic/omniauth-facebook/issues/196
    :token_params => {
      parse: :json
    }
```

**Comment by grouptable** [comment]
Just deployed by modifying config/initializer/devise.rb as below:
config.omniauth :facebook,
    5650971626448406,
    6ab7cbaa6b694d91fd559ef3facdf0936ab7cb,
    :scope => Rails.application.config.facebook.permissions,
    :display => "page",
    :client_options => {
      :site => "https://graph.facebook.com/v2.4",
      :authorize_url => "https://www.facebook.com/v2.4/dialog/oauth",
    },
    # https://github.com/mkdynamic/omniauth-facebook/issues/196
    :token_params => {
      parse: :json
    }
Not working. The response continues to be:
Given URL is not permitted by the Application configuration: One or more of the given URLs is not permitted by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

PS: Random strings are given above for app id & secret.

We are struggling to get a fix since we moved our server.

**Comment by grouptable** [comment]
How do we set the app_id and app_secret for different environments?

**Comment by mkdynamic** [comment]
Closing this in lieu of https://github.com/mkdynamic/omniauth-facebook/issues/190.
