### ISSUE TITLE
Not getting hometown in hash

### ISSUE THREAD

**Issue by tgoldenberg** [mkdynamic/omniauth-facebook#199]
Hi! For some reason, I'm not able to access the user's hometown. I can get the auth.info and auth.extra.raw_info hashes, but not finding the hometown. Any suggestion? Thanks :)

**Comment by simi** [comment]
Do you use proper scope (`user_hometown` probably)?

**Comment by tgoldenberg** [comment]
I've scoped for it but still not clear on what I'm supposed to pass in - some examples online show auth.info.location
auth.extra.raw_info.user_hometown  Can't get any to work. If someone knows the answer, please share. Otherwise I will close this, thanks.

**Comment by simi** [comment]
Is this solved? Can you post any informations? Feel free to reopen this. I'm going to try this soon.

**Comment by tgoldenberg** [comment]
So it seems to me that Facebook is making apps pass an authorization procedure, by submitting links to privacy policy, detailed description of authentication, etc. I tried to do this but the request was not accepted. It seems that now user_hometown falls under information that must be obtained in this way. If anyone can either confirm or refute this, I would be happy either way. This is what it seems like to me after having tried to access the user_hometown

**Comment by mkdynamic** [comment]
I'm not sure what the specific field is that you need to pass to get this info, but this does not seem like a bug. If anyone has suggestions please update.
