### ISSUE TITLE
[Question] How do you invite Facebook friends?

### ISSUE THREAD

**Issue by famousky** [mkdynamic/omniauth-facebook#202]
I cannot figure out how do you invite Facebook friends through this gem. Is there any example app out there I could check out?

**Comment by simi** [comment]
1. this is issue tracker, so please post issues only
2. "OmniAuth is a flexible authentication system utilizing Rack middleware", you can obtain user's `access_token` via this gem to interact with Facebook Graph API directly or via some library like [koala](https://github.com/arsduo/koala)..

**Comment by famousky** [comment]
@simi I almost got there but it seems like FB asking me for session key. 

![screen shot 2015-05-10 at 4 47 38 pm](https://cloud.githubusercontent.com/assets/4720153/7553598/4e45279c-f734-11e4-9960-dab4686e9b46.png)
Now:
1. Is session key = access_token ? 
2. How to obtain *access_token*
