### ISSUE TITLE
Can I call omniauth_facebook with short-lived access token ?

### ISSUE THREAD

**Issue by om-nishu-trantor** [mkdynamic/omniauth-facebook#203]
I have short-lived access token from the SDK call.
I want to obtain all the raw_info, info, etc.
Can I call omniauth-facebook even if I am already authenticated just for the sake for fetching long-lived token and the access data I require(Omniauth provides through through it's server side o-auth call) ?

**Comment by simi** [comment]
We're getting [raw_info](https://github.com/mkdynamic/omniauth-facebook/blob/master/lib/omniauth/strategies/facebook.rb#L58) by hitting `https://graph.facebook.com/me?access_token=xxx` with valid access token. You can do the same manually easily.

**Comment by om-nishu-trantor** [comment]
@simi I got your point about the raw_info.
I am interested in creating a [auth_hash with same components that we have here](https://github.com/intridea/omniauth/blob/master/lib/omniauth/strategy.rb#L332)
It contains not only the ```:raw_info``` but `info`, `credentials` and `extra` as well.
Am I on the right track or not ?

**Comment by simi** [comment]
It's hard to tell. You can try to construct those manually. But I've never tried that.

`uid` is mapped by https://github.com/mkdynamic/omniauth-facebook/blob/b127c35135b16b7d5cdc746a718192acfe1da21c/lib/omniauth/strategies/facebook.rb#L31

`info` and `extra` are mapped by https://github.com/mkdynamic/omniauth-facebook/blob/b127c35135b16b7d5cdc746a718192acfe1da21c/lib/omniauth/strategies/facebook.rb#L33-L55

`credentials` are mapped by https://github.com/intridea/omniauth-oauth2/blob/64a4f97f3eb158279e79f3bc598dcd337a5c23ab/lib/omniauth/strategies/oauth2.rb#L39-L45

And all these mappings are defined in https://github.com/intridea/omniauth/blob/master/lib/omniauth/strategy.rb#L90-L110.

Can I ask you what are you trying to achieve? Maybe there's a better way to do it.

**Comment by om-nishu-trantor** [comment]
@simi In my application I use omniauth for various strategies, there's one landing point for all strategies and the way we save data, now we need to use login using the Facebook SDK due to some reasons and in a way that fron-end will authenticate and pass on a shot lived token and I want to build this omniauth-hash manually so that we need not to use a separate logic for strategy facebook.
