### ISSUE TITLE
development.json for facebook authentication

### ISSUE THREAD

**Issue by shafaiatul** [mkdynamic/omniauth-facebook#205]
First of all you have to create an app going to >   https://developers.facebook.com/
It will produce the secret_id and app_id for your application. I have mentioned the development.json file for the facebook authentication: 

{
	"dbURL" : "mongodb://chatcatuser:mychatapp@********.mongolab.com:47307/*****",
	"sessionSecret" : "ASKJDLAJD234234LKJ2342ASD3JL",
	"fb" : {
		"appID" : "328577890650792",
		"appSecret" : "0fa907653387g6c2aeb26f8f3674a24b",
		"callbackURL" : "http://localhost:3000/auth/facebook/callback"
	},
	"host" : "http://localhost:3000"
}

**Comment by simi** [comment]
Hello @shafaiatul. Sorry, but I can't see what issue are you facing. Can you provide some details?

**Comment by mkdynamic** [comment]
Closing this due to lack of info, please update if you have more details and we'll take another look.
