### ISSUE TITLE
omniauth-facebook cannot sign in from sub domain.

### ISSUE THREAD

**Issue by RathanakSreang** [mkdynamic/omniauth-facebook#207]
I've face one problem when I want to allow user sign from sub domain. I have create FB app with "lvh.me:3000" and this working find when I sign in from that  url. But when I want to allow user sign from sub domain Ex "abc.lvh.me:3000" it have an error which I cannot sign in. And I do research on google I found one solution like this:
```ruby
<%= link_to "Sign with FB", user_omniauth_authorize_url(:facebook, subdomain: false), class: "btn btn-facebook" %>
```
and It is work find but after sign in it did not redirect to "abc.lvh.me:3000" but it redirect to "lvh.mr:3000" in stead. so do you know how can I solve this problem?

**Comment by simi** [comment]
Hello @RathanakSreang!

You can define callback path via `callback_path` proc passed to provider in OmniAuth builder.

```ruby
provider :facebook, ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_APP_SECRET'], :callback_path => "my/callback/url"
```

Also you can try approach mentioned on [Setup Phase OmniAuth](https://github.com/intridea/omniauth/wiki/Setup-Phase) wiki page.

**Comment by mkdynamic** [comment]
Looks like the solution suggested by @simi solves this, so closing for now. Please update or open a PR if you think we need changes to support this better. Thanks!
