### ISSUE TITLE
Omniauth devise Authentication failure! csrf_detected:

### ISSUE THREAD

**Issue by poc7667** [mkdynamic/omniauth-facebook#208]
I got the  `Authentication failure! csrf_detected:`  so that I couldn't login with omniauth.

I followed this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-configure-devise-and-omniauth-for-your-rails-application)

and I found similar issue [here](https://github.com/mkdynamic/omniauth-facebook/issues/73), 

But there are no luck for my problem till now.

Any idea for fixing the error ? Thanks

    E, [2015-06-27T10:40:06.028200 #18798] ERROR -- omniauth: (facebook) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

# Gems

      * devise (3.5.0)
      * omniauth (1.2.2)
      * omniauth-facebook (2.0.0)
      * omniauth-oauth2 (1.3.1)

# /app/controllers/application_controller.rb

       protect_from_forgery with: :exception
    -
    +  before_action :authenticate_user!

# /app/models/user.rb

       devise :database_authenticatable, :registerable,
    +         :omniauthable, :omniauth_providers => [:facebook]
    +  def self.from_omniauth(auth)
    +    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    +      binding.pry
    +      user.provider = auth.provider
    +      user.uid = auth.uid
    +      user.email = auth.info.email
    +      user.password = Devise.friendly_token[0,20]
    +    end
    +  end
    +

# /config/initializers/omniauth.rb

    +Rails.application.config.middleware.use OmniAuth::Builder do
    +  provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET'],
    +   :scope => 'email'
    +end

# Error log from console (how to trace it?)

    Started GET "/users/auth/facebook/callback?code=AQDZC-Ny2PI-UwunCNi29mx4YGKT&state=cf896d3decffe2a7a664315e050a1165a290477542ff7d33" for 127.0.0.1 at 2015-06-27 10:40:05 +0800
    I, [2015-06-27T10:40:05.255832 #18798]  INFO -- omniauth: (facebook) Callback phase initiated.
    I, [2015-06-27T10:40:06.028051 #18798]  INFO -- omniauth: (facebook) Callback phase initiated.
    E, [2015-06-27T10:40:06.028200 #18798] ERROR -- omniauth: (facebook) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
    Processing by CallbacksController#failure as HTML
      Parameters: {"code"=>"AQDZC-Ny2PI-UwunCNi29mx4YGKTuHDeP2X2X-leywO14gr_iHLvXxX1LpV5WteUrQHpX-uc0Z01wcjy4XHA9CBkZeSo4qRb7jXdvPLfQl6mgwbMrFuQb1_55KughvtMWMlZ_7YEhtiLoEZH_2EvGXLbuKkUq", "state"=>"cf896d3decffe2a7a663"}

# routes

    +  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

**Comment by rodrigoargumedo** [comment]
What happens if you remove..

```ruby
binding.pry # from User model
```

Does it work with CSRF getting it raised?

**Comment by simi** [comment]
Hello @poc7667. Does the [example app](https://github.com/mkdynamic/omniauth-facebook/blob/master/example/app.rb) work for you? Can you modify example app or provide minimal Rails application to replicate your problem?

**Comment by sophie-li** [comment]
I have similar problem too. 

My code is heavily inspired from this blogpost: http://sourcey.com/rails-4-omniauth-using-devise-with-twitter-facebook-and-linkedin/

More details on stackoverflow: http://stackoverflow.com/questions/31691283/rails-4-omniauth-facebook-csrf-detected

**Comment by dmcbrayer** [comment]
I think part of the problem may be in your omniauth initializer.  Since Facebook updated their API to v2.4 in early July, they appear to be requiring us to specifically ask for `info_fields` in the auth request.  Would suggest you change your initializer to the following:

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET'],
   :scope => 'email',
   :info_fields => 'email'
end
```
I was using the above referenced blog post as well (http://sourcey.com/rails-4-omniauth-using-devise-with-twitter-facebook-and-linkedin/) and ran into this problem, and adding the above fix solved my issue.

It's also now mentioned in the devise wiki:   https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview

**Comment by mkdynamic** [comment]
Can you check if this is fixed in 3.0.0?

**Comment by prashant4224** [comment]
Still the issue remains same

    Started GET "/users/auth/facebook" for 127.0.0.1 at 2015-10-30 01:30:13 +0530
    I, [2015-10-30T01:30:13.483854 #10255]  INFO -- omniauth: (facebook) Request phase initiated.


    Started GET "/users/auth/facebook/callback?code=AQDeo5qj0l9Gii6I6AYND6p2OEESDQ_cDS9lFqoqQoAvzR_Ka_9l5-nMH1KACoUDuI72Nl-G9mYYrDZfrxkDBLUWV8jkz2sV-7MV21-vKPE6cAeoIbrE4wOJNVwE_pcyyZwsxFZIRLn-qzmbjB1iPPmoIl4zZlRyx3UGqWipNaOSylEHxCsHeVF0whIAe5cDsDfH5FSF_HubnzfgVC-MXT3uMR2myphWlnXjQYKhZfZrRW-BqueK0ZXIeGDKQjX2rw9VilLsp9d_QWBJ5WscwIo-4GNgfUxCT4u5zHCFlvwszIw222cZmArddQsI7ojHitn6eo2QMlUzldLpUn5eSdMs&state=753edbb8d0e7e7ee059296fa21f34f55730bfb99355a97d5" for 127.0.0.1 at 2015-10-30 01:30:15 +0530
    I, [2015-10-30T01:30:15.613178 #10255]  INFO -- omniauth: (facebook) Callback phase initiated.
    E, [2015-10-30T01:30:15.614205 #10255] ERROR -- omniauth: (facebook) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
    Processing by Users::OmniauthCallbacksController#failure as HTML
    Parameters: {"code"=>"AQDeo5qj0l9Gii6I6AYND6p2OEESDQ_cDS9lFqoqQoAvzR_Ka_9l5-nMH1KACoUDuI72Nl-G9mYYrDZfrxkDBLUWV8jkz2sV-7MV21-vKPE6cAeoIbrE4wOJNVwE_pcyyZwsxFZIRLn-qzmbjB1iPPmoIl4zZlRyx3UGqWipNaOSylEHxCsHeVF0whIAe5cDsDfH5FSF_HubnzfgVC-MXT3uMR2myphWlnXjQYKhZfZrRW-BqueK0ZXIeGDKQjX2rw9VilLsp9d_QWBJ5WscwIo-4GNgfUxCT4u5zHCFlvwszIw222cZmArddQsI7ojHitn6eo2QMlUzldLpUn5eSdMs", "state"=>"753edbb8d0e7e7ee059296fa21f34f55730bfb99355a97d5"}
    
![screenshot from 2015-10-30 01 32 23](https://cloud.githubusercontent.com/assets/1472295/10830960/a424c37e-7ea8-11e5-9957-beafcdddaab4.png)
Redirected to http://localhost:3000/

**Comment by sibinx7** [comment]
```
Started GET "/users/auth/facebook/callback?code=AQCktKsTjD9C7cqQX4FjKF0VOvNg46viA0NF3tm0q1xesmkDx9PAPzB7FhwBQ3_QrONI7TzkNWxsevilyrej7uC7jpLTSoEe9Eel4XRL41pEKveaEzqnlP2Pj1NVxSrY7V1F9ZsIVrJqfNNOkuxLr_MSs7ffLMpDltoHvgLZQQ6ATbW6dnQfbIT7ChoMbWOyC0xsimGGZQMqCawBFidlWYlFn6Xct3_8l9qCu8L-68oV7cyRNEBUEL9f6El2DslCRWXsYlX4fyQnVU_CJqVEPtSpVtYx9ddRHZkSjizMUB_Vj5GEZHDomujY6yl2P9BRtdZahuM3j5eX72euii-8t2vs&state=f2db5a669ca1eaa8441af53256b1659b4896758fa6e094fa" for 192.168.1.16 at 2015-11-13 15:32:23 +0530
I, [2015-11-13T15:32:23.295275 #3826]  INFO -- omniauth: (facebook) Callback phase initiated.
I, [2015-11-13T15:32:27.338959 #3826]  INFO -- omniauth: (facebook) Callback phase initiated.
E, [2015-11-13T15:32:27.339215 #3826] ERROR -- omniauth: (facebook) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
Processing by Users::OmniauthCallbacksController#failure as HTML
  Parameters: {"code"=>"AQCktKsTjD9C7cqQX4FjKF0VOvNg46viA0NF3tm0q1xesmkDx9PAPzB7FhwBQ3_QrONI7TzkNWxsevilyrej7uC7jpLTSoEe9Eel4XRL41pEKveaEzqnlP2Pj1NVxSrY7V1F9ZsIVrJqfNNOkuxLr_MSs7ffLMpDltoHvgLZQQ6ATbW6dnQfbIT7ChoMbWOyC0xsimGGZQMqCawBFidlWYlFn6Xct3_8l9qCu8L-68oV7cyRNEBUEL9f6El2DslCRWXsYlX4fyQnVU_CJqVEPtSpVtYx9ddRHZkSjizMUB_Vj5GEZHDomujY6yl2P9BRtdZahuM3j5eX72euii-8t2vs", "state"=>"f2db5a669ca1eaa8441af53256b1659b4896758fa6e094fa"}
{"code"=>"AQCktKsTjD9C7cqQX4FjKF0VOvNg46viA0NF3tm0q1xesmkDx9PAPzB7FhwBQ3_QrONI7TzkNWxsevilyrej7uC7jpLTSoEe9Eel4XRL41pEKveaEzqnlP2Pj1NVxSrY7V1F9ZsIVrJqfNNOkuxLr_MSs7ffLMpDltoHvgLZQQ6ATbW6dnQfbIT7ChoMbWOyC0xsimGGZQMqCawBFidlWYlFn6Xct3_8l9qCu8L-68oV7cyRNEBUEL9f6El2DslCRWXsYlX4fyQnVU_CJqVEPtSpVtYx9ddRHZkSjizMUB_Vj5GEZHDomujY6yl2P9BRtdZahuM3j5eX72euii-8t2vs", "state"=>"f2db5a669ca1eaa8441af53256b1659b4896758fa6e094fa"}
Redirected to http://politics.dev:3000/
Completed 302 Found in 1ms (ActiveRecord: 0.0ms)
```
Same issues, Can't connect with Facebook with omniauth-facebook

**Comment by sibinx7** [comment]
Can anyone post an working example with device, omniauth-facebook... I tried many time but got same error...

**Comment by sibinx7** [comment]
It is not gem's issues,it is my mistake,  i have added configuration on both device.rb initializer and a newly created omniauth.rb initializer, after removing everything from omniauth.rb and restart server, i got facebook datas...
