### ISSUE TITLE
:first_name returns extraneous info other than first name

### ISSUE THREAD

**Issue by rodrigoargumedo** [mkdynamic/omniauth-facebook#210]
@mkdynamic 

Right where I was testing my Rails app, it returned all of the DB info other with first name and last name. I scoped it with ```user.first_name``` that assigns to ```auth.info.first_name```. I'm not sure if this is the correct way of returning the first name:

```ruby
["Rodrigo", "Argumedo", "rodrigo.argumedo@outlook.com", "sss", "Rodrigo Argumedo", nil, "Kingwood, Texas", "http://graph.facebook.com/10153203366797241/picture", "yyy", nil, 1442000989]
```

Although, this is an issue that I only encountered throughout the test. This bug also applies to ```auth.extra.raw_info.first_name```

**Comment by mkdynamic** [comment]
Not sure I follow. Can you supply a test case that reproduces the problem?

**Comment by John222** [comment]
Hi. I am expierencing the same issue. When i try to refer **auth.extra.raw_info.first_name** or **auth.first_name** i get no information. I am using omniauth 1.3.1 with omniauth-facebook 3.0.0.0.

Same is for **last_name** and **gender**. All information should be available by the default permission  **default_profile**

**Comment by mapreal19** [comment]
@John222 see #214. You need to add `info_fields` in your config:

    config.omniauth :facebook, ..., info_fields: 'first_name, last_name'

Found answer here: http://stackoverflow.com/a/33095669/2273578
