### ISSUE TITLE
Only getting minimal fields sent to /callback

### ISSUE THREAD

**Issue by rjcoupe** [mkdynamic/omniauth-facebook#211]
`provider :facebook, ENV['FACEBOOK_APP_ID'], ENV['FACEBOOK_APP_SECRET'], scope: ['email', 'public_profile']`

The authorization appears to succeed, but I only receive basic fields in the callback payload:

````
{
    "provider":"facebook",
    "uid":<redacted>,
    "info":{
        "name":<redacted>,
        "image":<redacted>,
        "credentials":{
            "token":<redacted>,
            "expires_at":1442319308,
            "expires":true
        },
        "extra":{
            "raw_info":{
                "name":<redacted>,
                "id":<redacted>
            }
        }
    }
}
````

I can't find anything wrong with my code, judging by docs I've found and followed. Is this a bug?

**Comment by simi** [comment]
You need to provide `info_fields` parameter with needed fields. See `info_fields` in [README.md](https://github.com/mkdynamic/omniauth-facebook#configuring). [Fix](https://github.com/mkdynamic/omniauth-facebook/pull/209) to get email by default will be probably merged soon
