### ISSUE TITLE
Email, gender, age  not  returned with Omniauth and facebook API 2.4

### ISSUE THREAD

**Issue by poc7667** [mkdynamic/omniauth-facebook#212]
I could __NOT__ get back the email information anymore with `Omniauth`.

I think the problem is duing to the API 2.4, 

But I don't get how could I the the expected information

# Devise config

    config.omniauth :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET'], {
      :scope => 'email',
      :info_fields => 'id,email,gender,link,locale,name,timezone,updated_time,verified',
      strategy_class: OmniAuth::Strategies::Facebook,
      :provider_ignores_state => true}

# Returned information not including email information

    :1> env['omniauth.auth']
    {
           "provider" => "facebook",
                "uid" => "xxxx",
               "info" => {
             "name" => "Eric Hsu",
            "image" => "http://graph.facebook.com/xxxx/picture?type=square"
        },
        "credentials" => {
                 "token" => "CAAh",
            "expires_at" => 1443066205,
               "expires" => true
        },
              "extra" => {
            "raw_info" => {
                "name" => "Eric Hsu",
                  "id" => "xxxx"
            }
        }
    }

![](https://i.imgur.com/S231OOf.png)

**Comment by simi** [comment]
There's no guarantee for email field. When email is not provided by FB API, you need to ask your user in your app for it. You can spot similar issues in issue tracker.
