### ISSUE TITLE
Not getting nickname in info hash

### ISSUE THREAD

**Issue by justinschier** [mkdynamic/omniauth-facebook#214]
Authentication is working as expected, but my app relies on having the nickname, and it's not coming through in the info at all. I get name, image url, etc., but not nickname. I've looked through the FB API docs and can't find anything about it.

Here's my config:
```
config.omniauth :facebook,  ENV["FACEBOOK_APP_ID"], ENV["FACEBOOK_SECRET"], :strategy_class => OmniAuth::Strategies::Facebook, scope: "email, public_profile, publish_actions"
```

**Comment by andrewmartin** [comment]
I'm having a similar issue and I cannot see even the email field. I had the config set up exactly as you had it and I cannot get the email to come through.

**Comment by bennylin77** [comment]
me too, no email, first_name, last_name
and my facebook api version is v2.4

**Comment by indie-rok** [comment]
1 + more with the problem

**Comment by indie-rok** [comment]
Fixed it

I just had to add this line to initializers/facebook.rb

     :info_fields => 'id,email,gender,link,locale,name,timezone,updated_time,verified'

**Comment by mkdynamic** [comment]
Refer to the fix suggested by https://github.com/mkdynamic/omniauth-facebook/issues/214#issuecomment-136025923.
