### ISSUE TITLE
Still FB not returning email for some users

### ISSUE THREAD

**Issue by adolfopeccin** [mkdynamic/omniauth-facebook#216]
Hello, it's weird but still happening to me something like this (https://github.com/mkdynamic/omniauth-facebook/issues/61):

I tried fix using this branch master v2.1.0 and setting info_fields but no success.

My config for omniauth on devise:
```
config.omniauth :facebook, "123", "123", scope: 'email,public_profile,user_about_me,user_birthday,user_location', info_fields: 'email,first_name,last_name,birthday,gender'
```

And then how I handle it on user model:
```
def self.find_for_facebook_oauth(auth)
    if user = User.where(:provider => auth.provider, :uid => auth.uid).first
      return user
    else
      if User.where(email: auth.info.email).exists?
        user = User.where(email: auth.info.email).first
        user.provider = auth.provider
        user.uid = auth.uid
        if !user.confirmed?
          user.skip_confirmation!
        end
        return user
      else
        if auth.info.email.present?
          user = User.new(provider: auth.provider,    
                          uid: auth.uid,
                          email: auth.info.email,
                          password: Devise.friendly_token[0,20])
          user.skip_confirmation!
          user.create_profile(name: auth.info.first_name, lastname: auth.info.last_name, username: auth.info.nickname,
                              birthday: Date.strptime(auth.extra.raw_info.birthday,'%m/%d/%Y'), gender: auth.extra.raw_info.gender)
          user.save
          return user
        end
      end
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
```

And Omniauth callback:
```
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end
```

The problem still for me, FB isn't returning email on auth... Does anyone have any clue about that?

**Comment by l0c0luke** [comment]
did you restart your rails server?

**Comment by erpe** [comment]
same thing here: app using facebook-api v2.4 -
some include email, some not. 
point at facebook...

**Comment by l0c0luke** [comment]
the other thing is your users do not HAE to give their email... when the box pops up, it allows them to uncheck it.

**Comment by adolfopeccin** [comment]
Yup. User can uncheck the email field @ auth, but I checked facebook profile with the problem and email is checked to give their email... :(

**Comment by FuriouZz** [comment]
I make the test on rails and I got the same problem.

I try in front same thing. Then I discover the `fields` params which needs what I want.

```
  FB.api('/me', {fields: 'email,picture,first_name,last_name,birthday'}, function(response) {
    console.log(response)
  });
```

Maybe your gem needs some changes?

**Comment by prashaantt** [comment]
Looks like there's a kind of breaking change in v2.4. From the [2.4 release notes](https://developers.facebook.com/blog/post/2015/07/08/graph-api-v2.4/):

> **Fewer default fields for faster performance:** To help improve performance on mobile network connections, we've reduced the number of fields that the API returns by default. You should now use the ?fields=field1,field2 syntax to declare all the fields you want the API to return.

So @FuriouZz is on the right track. [Hybridauth](https://github.com/hybridauth/hybridauth/commit/e8015af23cc9b5aaa3755508b4d8117df8ceda5a) has a similar fix.

**Comment by Overload119** [comment]
I just started seeing this error a few days ago.
Is there a way to resolve this without using some code on the front-end?

**Comment by FuriouZz** [comment]
I tried the devise solution and it works for me : https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview#facebook-returning-nulled-email

**Comment by Overload119** [comment]
Perfect - I had run those instructions but was running an older version of `omniauth-facebook`.

**Comment by Overload119** [comment]
Ugh - still getting this error, but it's coming from users on mobile phones typically.

I have:

```
config.omniauth :facebook,
                  Rails.application.secrets.facebook_app_id,
                  Rails.application.secrets.facebook_app_secret,
                  scope: "email",
                  info_fields: "email,name"
```

```
    devise (3.4.1)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
omniauth (1.2.2)
      hashie (>= 1.2, < 4)
      rack (~> 1.0)
    omniauth-facebook (2.0.1)
      omniauth-oauth2 (~> 1.2)
    omniauth-oauth2 (1.3.1)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
```

You can actually try it out live: 
http://www.rappad.co/?show_login=true

Notice, as soon as the button is clicked apparently there's an error in the URL, as seen in "user_error=access_denied".

`https://www.facebook.com/login.php?skip_api_login=1&api_key=188262358022447&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fv2.0%2Fdialog%2Foauth%3Fredirect_uri%3Dhttp%253A%252F%252Fwww.rappad.co%252Fusers%252Fauth%252Ffacebook%252Fcallback%26display%3Dpopup%26state%3D7b31f73828fedfa32b533c9f2570314f91e46db3f48e46b6%26scope%3Demail%26response_type%3Dcode%26client_id%3D188262358022447%26ret%3Dlogin&cancel_url=http%3A%2F%2Fwww.rappad.co%2Fusers%2Fauth%2Ffacebook%2Fcallback%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3D7b31f73828fedfa32b533c9f2570314f91e46db3f48e46b6%23_%3D_&display=popup`

I can't reproduce this locally, I can just see the reports coming in, with the auth info not being there.

```
 * omniauth.auth                                  : {"provider"=>"facebook", "uid"=>"[REDACTED]", "info"=>{"name"=>"[REDACTED]", "image"=>"[REDACTED]"}, "credentials"=>{"token"=>"[REDACTED]", "expires_at"=>1448646407, "expires"=>true}, "extra"=>{"raw_info"=>{"name"=>"[REDACTED]", "id"=>"[REDACTED]"}}}
```

**Comment by adolfopeccin** [comment]
Still happening. Maybe implement something like that? check: https://github.com/hybridauth/hybridauth/commit/e8015af23cc9b5aaa3755508b4d8117df8ceda5a

**Comment by mkdynamic** [comment]
Email is requested by default in 3.0.0. https://github.com/mkdynamic/omniauth-facebook/blob/master/CHANGELOG.md#300-2015-10-26

**Comment by adolfopeccin** [comment]
Checked 3.0.0 and email still not returned for me :(

**Comment by shahidaali** [comment]
Facebook will not return the email for those users whose email is pending for confirmation, when a user creates new account on facebook a confirmation email is sent to the user, but if user did't confirm his email, facebook will not return his email in user info even you added email permission in scope, until user confirms his email.

**Comment by JulioOrellana** [comment]
Hello, I am using my personal account for a private app using this gem, I use facebook years ago and I am not receiving email either. I don't understand why is this happening.

**Comment by adolfopeccin** [comment]
@JulioOrellana did you confirmed your email @ Facebook?

**Comment by JulioOrellana** [comment]
@adolfopeccin yes, I am fixing this app because it has some problemas but the company doesn't have to facebook credentials of the app so I create one for them only so I changed secret and app_id, after that it started making this problem.

"info" only includes "name" and "Image" on json and no other file includes "email" anymore :/.

My app is public and I am using Client and Web OAuth

**Comment by aliceclv** [comment]
@JulioOrellana hey, did you solve your problem ? I'm encountering the same difficulties...

**Comment by JulioOrellana** [comment]
@aliceclv no, I ended up using the old credentials because I couldn't obtatin what I wanted.
