### ISSUE TITLE
Email isn't being received even if Facebook says that it was sent

### ISSUE THREAD

**Issue by mrodrigues** [mkdynamic/omniauth-facebook#218]
I'm working in two applications using `devise` and `omniauth-facebook`. Both are using the same configuration:
```
config.omniauth :facebook, ENV["FACEBOOK_APP_ID"], ENV["FACEBOOK_APP_SECRET"], scope: 'email', info_fields: 'email, name'
```
One of them works without any problems, but the other one isn't returning the email, even though when I inspect the app's permissions in my Facebook account it says that the email was sent.

I've also included a code to rerequest the email if the user didn't give permission, and when I explicitly uncheck the email field, instead of showing a new modal asking for permission to get the email, it immediately returns without the email again, starting an infinite redirect loop.

Is this a bug in `omniauth-facebook`, the Facebook API or is this configuration wrong? I can't imagine why it's working differently between apps even though the configuration is the same.

**Comment by rajputvai** [comment]
Please check this thread. https://github.com/mkdynamic/omniauth-facebook/pull/209

**Comment by realmensah** [comment]
Figured this out. You need to add the scope on fb login response. Change:

$('#sign_in').click (e) ->
    e.preventDefault()
    FB.login (response) ->
      window.location = '/auth/facebook/callback' if response.authResponse

To:

$('#sign_in').click (e) ->
    e.preventDefault()
    FB.login ((response) ->
      window.location = '/auth/facebook/callback' if response.authResponse), scope: "email"

**Comment by vemv** [comment]
@mrodrigues is this still an issue? Two people have pointed out tips.

Else please close it.

Cheers - Victor

**Comment by mrodrigues** [comment]
Yes, it's still happening. I already have the `scope` and `info_fields`, and it's the same exact configuration for both of my applications. I make a rerequest with `redirect_to "/users/auth/facebook?auth_type=rerequest&scope=email"`, and it starts a infinite redirect loop on one of them. It's like if I had already gave permission for the application, but the email field consistently doesn't come in the response.

**Comment by mkdynamic** [comment]
Can you check if 3.0.0 fixes this?
