### ISSUE TITLE
Omniauth-facebook version 2.0.1 or 2.1.0 in regards to signed_request.rb

### ISSUE THREAD

**Issue by urbanvikingr** [mkdynamic/omniauth-facebook#219]
Omniauth-facebook gem says version 2.0.1 - February 21, 2015 (17.5 KB), but the version.rb in omniauth-face says version 2.1.0.

Is there a version on its way?

I noticed that signed_request.rb has been changed recently. Please could you tell if that change has been published.

While using the client-side flow, I'm getting an error message from Facebook that the signed requested has an invalid code format.

The signed request is passed from omniauth-facebook to Facebook.

My versions:
omniauth-facebook 2.0.1
omniauth-oauth2 1.3.1
oauth2 1.0.0
omniauth 1.2.2
facebook api 2.5
rails 4.2.4
rack 1.6.4

**Comment by mkdynamic** [comment]
2.1.0 was never released. 3.0.0 was just released which contains changes originally slated for 2.1.0.
