### ISSUE TITLE
Can't install latest version with rails 5beta1

### ISSUE THREAD

**Issue by diegosky1** [mkdynamic/omniauth-facebook#232]
After bundle install the gem with version 3.0, I get this...
Bundler could not find compatible versions for gem "rack":
  In snapshot (Gemfile.lock):
    rack (= 2.0.0.alpha)

  In Gemfile:

    simple_form (>= 0) ruby depends on
      actionpack (< 5.1, > 4) ruby depends on
        rack-test (~> 0.6.3) ruby depends on
          rack (>= 1.0) ruby

    rails (< 5.1, >= 5.0.0.beta1) ruby depends on
      sprockets-rails (>= 2.0.0) ruby depends on
        sprockets (>= 3.0.0) ruby depends on
          rack (< 3, > 1) ruby

    simple_form (>= 0) ruby depends on
      actionpack (< 5.1, > 4) ruby depends on
        rack (~> 2.x) ruby

    omniauth (>= 0) ruby depends on
      rack (< 3, >= 1.0) ruby

    simple_form (>= 0) ruby depends on
      actionpack (< 5.1, > 4) ruby depends on
        rack-test (~> 0.6.3) ruby depends on
          rack (>= 1.0) ruby

    omniauth-facebook (~> 3.0) ruby depends on
      omniauth-oauth2 (~> 1.2) ruby depends on
        oauth2 (~> 1.0) ruby depends on
          rack (~> 1.2) ruby

**Comment by simi** [comment]
We're waiting for [oauth2 new release](https://github.com/intridea/oauth2/commit/43e1fdd87e95a5b02438d5cce6a67e411afb5fec). Meanwhile you can use latest master branch:

```ruby
gem 'oauth2', github: 'intridea/oauth2'
gem 'omniauth-facebook', '~> 3.0'
```
