### ISSUE TITLE
Cannot access some info fields from the public profile

### ISSUE THREAD

**Issue by Uelb** [mkdynamic/omniauth-facebook#234]
These info fields cannot be accessed via the gem although they are sent by default by facebook.
- age_range
- verified
- gender
- timezone
- locale

https://developers.facebook.com/docs/facebook-login/permissions?locale=fr_FR#reference-public_profile

**Comment by mkdynamic** [comment]
PR welcome!

You can still get these via the raw_info part of the hash.
