### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by admazzola** [mkdynamic/omniauth-facebook#238]
So Im getting this weird error - it pops up on some of my dev environments but not others.  Its been creeping into more and more of them and it totally breaks my omniauth login!   After I do the sign-in on facebooks page and get redirected back to my site, the big red rails error screen appears with the following...

```

Faraday::ConnectionFailed
Connection reset by peer

Extracted source (around line #153):
               
    def rbuf_fill
      begin
        @rbuf << @io.read_nonblock(BUFSIZE)
      rescue IO::WaitReadable
        if IO.select([@io], nil, nil, @read_timeout)
          retry

```

Please help! o.o

**Comment by mkdynamic** [comment]
Closing this since is old and it looks like a networking issue, not related to this gem.
