### ISSUE TITLE
Fix test suite for 1.9.2 and rbx

### ISSUE THREAD

**Issue by sribalakumar** [mkdynamic/omniauth-facebook#240]

**Comment by simi** [comment]
hmm, are you interested in?

For 1.8.7 and 1.9.2 I think only lower rake version is needed (can be locked in Gemfile just for ruby_19 and ruby_18 platforms).

I have no idea what's going on in rbx build.

**Comment by mkdynamic** [comment]
Next version will require 1.9.3+, build is updated accordingly.
