### ISSUE TITLE
jwt version conflict prevents installation alongside omniauth-google-oauth2

### ISSUE THREAD

**Issue by BigMcLargeHuge** [mkdynamic/omniauth-facebook#241]
I've run into a situation where I'm trying to enable authorization through both  Facebook and Google via the `omniauth-facebook` and `omniauth-google-oauth2` gems respectively.  However both rely on different versions of the jwt gem, leading to the following conflict:

```
Bundler could not find compatible versions for gem "jwt":
  In snapshot (Gemfile.lock):
    jwt (= 1.5.1)

  In Gemfile:
    jwt (~> 1.5.1)

    omniauth-facebook (~> 3.0) was resolved to 3.0.0, which depends on
      omniauth-oauth2 (~> 1.2) was resolved to 1.4.0, which depends on
        oauth2 (~> 1.0) was resolved to 1.1.0, which depends on
          jwt (< 1.5.2, ~> 1.0)

    omniauth-google-oauth2 (~> 0.4.1) was resolved to 0.4.1, which depends on
      jwt (~> 1.5.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by simi** [comment]
This probably fixed in https://github.com/intridea/oauth2/commit/e0006cb5099bf392f011eb5c49cbec4f893bbdba. You'll need to wait for new release or use directly oauth2 gem from master.

**Comment by mkdynamic** [comment]
This is an issue in `oauth2` as @simi mentioned.
