### ISSUE TITLE
How do I refresh the token when it expired, without the user having to log in again?

### ISSUE THREAD

**Issue by nonato** [mkdynamic/omniauth-facebook#242]
Good evening.

Is there a way to renew the token after it is expired without the user having to log in again?

When I do authentication with google, I get a "refresh_token" which allows me to generate a new "access_token", when it expires.

That way, I do not need to force the user to log in again to generate a new token

Is there any way to do this with the gem "ominiauth-facebook"?

THanks!!

**Comment by mkdynamic** [comment]
Please review the README docs for `auth_type` and the FB docs here:
https://developers.facebook.com/docs/facebook-login/reauthentication/
