### ISSUE TITLE
OmniAuth::NoSessionError

### ISSUE THREAD

**Issue by alanwillms** [mkdynamic/omniauth-facebook#246]
When using `omniauth-facebook` `3.0.0` with a API-only Rails 5 application, I get this error:

`OmniAuth::NoSessionError (You must provide a session to use OmniAuth.)`

It seems the issue has already been solved by `omniauth-oauth2` `1.3.1`, but this gem requires version `1.2`.

Is there a workaround?

**Comment by simi** [comment]
Let's see if we can upgrade also.

**Comment by mkdynamic** [comment]
@alanwillms This gem only requires `~> 1.2` for `omniauth-oauth2`, so you should be able to use `1.3` (or `1.4`) in your app. If you're using Bundler, specify this in your Gemfile:

```ruby
gem 'omniauth-facebook'
gem 'omniauth-oauth2', '1.3.1' # (or whatever version you want)
```

**Comment by mmahalwy** [comment]
hmm, I cannot get it to work even with 1.4. Still same error as above. Anyone experiencing same thing?
