### ISSUE TITLE
How to refresh expired token ?

### ISSUE THREAD

**Issue by rusikf** [mkdynamic/omniauth-facebook#252]
Hello ruby hackers!

Example:
 1) I saved token to db, and did some requests to fb with this token. 
 2) After some time, token will be expired
Question:
 How to refresh it ?

May be I need to log in again through omniauth-facebook, but with auth_type: 'reauthenticate' for refresh token or there is a more elegant way ?

**Comment by simi** [comment]
This out of scope of this library. You'll need to handle this on your own. See attached links.

https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension
http://stackoverflow.com/a/21879758/319233
