### ISSUE TITLE
Faraday::ConnectionFailed: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by joker-777** [mkdynamic/omniauth-facebook#253]
Hello,

we haven't changed anything but suddenly got this error
```
Faraday::ConnectionFailed: Connection reset by peer - SSL_connect
```
Does anyone experience the same problem? Do you guys know what the reason could be?

We use

omniauth-facebook: 3.0.0
omniauth: 1.3.1
ruby: 2.2.2p95 / 2.3.1

Thanks,

Johannes

**Comment by gingerlime** [comment]
I should probably add that it's intermittent. It works in ~90% of the cases, but occasionally fails with this error.

**Comment by gingerlime** [comment]
We were testing compiling ruby 2.3.1 on a new platform (same gem versions), and bumped into the same error again :-/

**Comment by simi** [comment]
I think this is not related to this library at all. `Connection reset by peer - SSL_connect` often means you're using unsupported handshake or similar case. This can be caused by OpenSSL version/config or something related to SSL communication.

**Comment by gingerlime** [comment]
Probably not, but we were hoping someone might be able to help. It happens some times with the same version/config of OpenSSL ...
