### ISSUE TITLE
access_token response not parsed correctly in 4.0

### ISSUE THREAD

**Issue by jpslav** [mkdynamic/omniauth-facebook#262]
FB authentication wasn't working for me in 4.0.0, but it works when I downgrade to 3.0.0.  The problem could be in my configuration, in the `oauth2` gem, or in `omniauth-facebook` -- I don't know, but I thought I'd post what I found here in case it is helpful to someone who knows more about the guts of these gems.

With 4.0.0, I was getting a response from FB, but it was erroring out with an "invalid_credentials" exception.  The error was getting raised here:

```
[135, 144] in ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/oauth2-1.2.0/lib/oauth2/client.rb
   135:       else
   136:         opts[:params] = params
   137:       end
   138:       response = request(options[:token_method], token_url, opts)
   139:       error = Error.new(response)
=> 140:       raise(error) if options[:raise_errors] && !(response.parsed.is_a?(Hash) && response.parsed['access_token'])
   141:       access_token_class.from_hash(self, response.parsed.merge(access_token_opts))
   142:     end
```

When I stepped into `response.parsed` I saw that the of the three available `parsers` (`:text`, `:query`, `:json`), the `:text` one was being used even though the `body` being parsed looks like a query string:

```
[66, 75] in ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/oauth2-1.2.0/lib/oauth2/response.rb
   66:     # The parsed response body.
   67:     #   Will attempt to parse application/x-www-form-urlencoded and
   68:     #   application/json Content-Type response bodies
   69:     def parsed
   70:       return nil unless @@parsers.key?(parser)
=> 71:       @parsed ||= @@parsers[parser].call(body)
   72:     end
   73: 
   74:     # Attempts to determine the content type of the response.
   75:     def content_type
(byebug) parser
:text
(byebug) body
"access_token=really_long_string_redacted_here&expires=5177519"
```

I didn't see where the choice of parser was coming from, but wanted to bring this up in case anyone runs into similar issues.

For completeness, the `invalid_credentials` error  came from here:

```
[73, 82] in ~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb
   73:           self.access_token = build_access_token
   74:           self.access_token = access_token.refresh! if access_token.expired?
   75:           super
   76:         end
   77:       rescue ::OAuth2::Error, CallbackError => e
=> 78:         fail!(:invalid_credentials, e)
```

**Comment by rubenfonseca** [comment]
Just adding that I have this problem too with 4.0.0. Downgrading works.

**Comment by giedriusr** [comment]
Using rails `4.2.7.1` locally no issues so far with 4.0.0.

**Comment by reidcooper** [comment]
I am having similar issues when trying to force my OmniAuth Facebook builder to use the v2.8 FB SDK. 

```
[67, 76] in /Users/reidcooper/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/oauth2-1.1.0/lib/oauth2/response.rb
   67:     #   Will attempt to parse application/x-www-form-urlencoded and
   68:     #   application/json Content-Type response bodies
   69:     def parsed
   70:       return nil unless @@parsers.key?(parser)
   71:       byebug
=> 72:       @parsed ||= @@parsers[parser].call(body)
   73:     end
   74:
   75:     # Attempts to determine the content type of the response.
   76:     def content_type
(byebug) @@parsers[parser].call(body)
{"{\"access_token\":\"RANDOM_STRING_OF_CHARACTERS\",\"token_type\":\"bearer\",\"expires_in\":5583}"=>nil}
```

That is what I am returned when using the v2.8 FB SDK. Once switching the sdks, removing as such below, it was able to successfully parse the response.

```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :facebook, FACEBOOK_SETTING[:app_id], FACEBOOK_SETTING[:app_secret],
           :scope => 'email',
           :display => 'popup',
           callback_path: "/auth/facebook/callback",
           client_options: {
               site: 'https://graph.facebook.com/v2.8',
               authorize_url: "https://www.facebook.com/v2.8/dialog/oauth"
           }
end

OmniAuth.config.logger = Rails.logger
```

I removed the client_options so it will default back to v2.6. That solved my problem. However, it would be nice to be able to use the v2.8 SDK.

**Comment by jpslav** [comment]
Upgrading to 4.0.0 and v2.8 of the FB API works for me.  I was previously on v2.0 of the FB API, so I'm guessing my problem was mixing very new and very old.  I'll leave this open; gem maintainers can close if they feel it is appropriate to do so.

**Comment by simi** [comment]
Thanks for info @jpslav!
