### ISSUE TITLE
Facebook id collision, or wrong user's auth hash infos received?

### ISSUE THREAD

**Issue by frederickdubois** [mkdynamic/omniauth-facebook#267]
Hi, 
I frowning at a very strange issue. 
I have some user accounts getting linked to the same facebook id... At first I thought this was a case of a public computer used by the 2 users but this theory has been dismissed... 

Has there ever been cases resported of wrong auth hash infos being returned in request.env['omniauth.auth']?
_(I feel stupid just for asking it... can't believe this could be possible... eheh But I really can't get a hold on how this might happen on my side...)_ 

I have a very specific case of a user who clearly said to me that he used the facebook option to create his account and ended up in the newly created account under somebody else's name.... I checked and indeed the account was created at that specific time and corresponded to someone else's facebook's infos... My app can't have _invented_ those informations, so how come did I receive them in the 1st place?

Now, I must admit that this website is long due for an update, it's on omniauth-facebook v1.4.1. I'm starting now to get this updated but still have a doubt that this will fix the issue...

Any help will be greatly appreciated!

**Comment by yuvi17** [comment]
@frederickdubois we've been using this gem for quite some time now and no such issue has been observed. Have you observed something similar again or was this a one-off incident?

**Comment by frederickdubois** [comment]
@yuvi17 I'm gonna close this issue as the problem did not happen again, probably related to my specific app

**Comment by CvX** [comment]
@frederickdubois A similar thing happened in my app (3-4 times over last two years). I couldn’t track it down. For a white I thought that maybe somehow `session` object (where I store the user id) got shared between requests. But this issue report got me thinking that maybe it was omniauth-facebook… 🤔

**Comment by frederickdubois** [comment]
I think the problem I had was that some users data did not contain an email and for those my app did not retrieve the correct user... something like that... 99.99% of FB users had an email but a small portion did not return any...

Been a while since I worked on this so I'm not totally sure... :)

**Comment by CvX** [comment]
Hm, that definitely wasn’t the case in my app. Here I had a closed environment with exactly 3 users, with all required data, and yet – some actions were logged as done by another user…
