### ISSUE TITLE
Update omniauth-oauth2 dependency to >= 1.3?

### ISSUE THREAD

**Issue by danielbonnell** [mkdynamic/omniauth-facebook#273]
Hi,

Is it possible to update the `omniauth-oauth2` dependency to `>= v1.3`?

Thanks in advance!

**Comment by simi** [comment]
The only direct dependency is [omniauth-oauth2](https://github.com/mkdynamic/omniauth-facebook/blob/19634473820d0190a5112f6b42266ef98c8ee276/omniauth-facebook.gemspec#L19). I think this is more upstream issue (as you linked). Or do you think there's something we can change here to solve this?

**Comment by danielbonnell** [comment]
Sorry I worded that very clumsily. I *think* upgrading the `omniauth-oauth2` dependency to `>= 1.3` would help solve my dependency problem. It looks like that gem dropped the `faraday` dependency at `1.3.0`. I'm in the process of trying to update several dependencies but am locked down because a few of my omniauth strategy gems have older Faraday dependencies.

**Comment by simi** [comment]
There's no need to update omniauth-oauth2 dependency here. You can lock whatever version fits ~> 1.2 constraint in your Gemfile.

example Gemfile:

```ruby
source 'https://rubygems.org'

gem 'omniauth-facebook'
gem 'omniauth-oauth2', '1.3'
```

is resolved into:

```ruby
GEM
  remote: https://rubygems.org/
  specs:
    faraday (0.10.1)
      multipart-post (>= 1.2, < 3)
    hashie (3.5.5)
    jwt (1.5.6)
    multi_json (1.12.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    oauth2 (1.3.0)
      faraday (>= 0.8, < 0.11)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.6.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-facebook (4.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-oauth2 (1.3.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    rack (2.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  omniauth-facebook
  omniauth-oauth2 (= 1.3)

BUNDLED WITH
   1.13.6
```

**Comment by danielbonnell** [comment]
Turns out `Oauth2`'s `faraday` constraint is the issue. Got kind of lost trying to follow the dependency chain. Thanks for your time.
https://github.com/intridea/oauth2/pull/291
