### ISSUE TITLE
Urgent, Facebook deprecation today, broke omniauth-facebook

### ISSUE THREAD

**Issue by jaequery** [mkdynamic/omniauth-facebook#277]
Just earlier today, we noticed that the omniauth-facebook no longer works. 
Upon quick search on Twitter it looks like Facebook has deprecated a few of their API and I feel this is the reason why FB auth stopped working for us.

Anyone else having this issue? Some urgent response would be greatly appreciated, thanks!

**Comment by simi** [comment]
See https://github.com/mkdynamic/omniauth-facebook/issues/276 for more info. Gem update should be enough.

**Comment by jaequery** [comment]
Thanks for the super quick response simi!

**Comment by jaequery** [comment]
The update to 4.0.0 resolved this issue for me. Thanks.
