### ISSUE TITLE
Bundler::GemRequireError: There was an error while trying to load the gem 'omniauth-facebook'.

### ISSUE THREAD

**Issue by giamma13** [mkdynamic/omniauth-facebook#281]
starting today we are having some strange problems when we run schema load on Codeship
- bundle exec rake db:schema:load

we have NOT changes anything in our Gemfile but we keep getting this error
- There was an error while trying to load the gem 'omniauth-facebook'.

anybody else having this problem ?

---

rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'omniauth-facebook'.
Gem Load Error is: undefined method `args' for OmniAuth::Strategies::OAuth2:Class
Backtrace for gem load error is:
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-oauth2-1.1.2/lib/omniauth/strategies/oauth2.rb:19:in `<class:OAuth2>'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-oauth2-1.1.2/lib/omniauth/strategies/oauth2.rb:16:in `<module:Strategies>'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-oauth2-1.1.2/lib/omniauth/strategies/oauth2.rb:10:in `<module:OmniAuth>'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-oauth2-1.1.2/lib/omniauth/strategies/oauth2.rb:9:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-facebook-1.6.0/lib/omniauth/strategies/facebook.rb:1:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-facebook-1.6.0/lib/omniauth/facebook.rb:2:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-facebook-1.6.0/lib/omniauth-facebook.rb:1:in `<top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `each'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `block in require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `each'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler.rb:108:in `require'
/home/rof/src/github.com/BEWE/ROIALTY/config/application.rb:14:in `<top (required)>'
/home/rof/src/github.com/BEWE/ROIALTY/Rakefile:4:in `require'
/home/rof/src/github.com/BEWE/ROIALTY/Rakefile:4:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/bin/rake:23:in `load'
/home/rof/cache/bundler/ruby/2.3.0/bin/rake:23:in `<top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:74:in `load'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:27:in `run'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli.rb:360:in `exec'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli.rb:20:in `dispatch'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli.rb:10:in `start'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/exe/bundle:35:in `block in <top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/exe/bundle:27:in `<top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
/home/rof/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
/home/rof/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/rof/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `each'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `block in require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `each'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler.rb:108:in `require'
/home/rof/src/github.com/BEWE/ROIALTY/config/application.rb:14:in `<top (required)>'
/home/rof/src/github.com/BEWE/ROIALTY/Rakefile:4:in `require'
/home/rof/src/github.com/BEWE/ROIALTY/Rakefile:4:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:74:in `load'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:27:in `run'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli.rb:360:in `exec'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli.rb:20:in `dispatch'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli.rb:10:in `start'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/exe/bundle:35:in `block in <top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/exe/bundle:27:in `<top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
/home/rof/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
/home/rof/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/rof/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `args' for OmniAuth::Strategies::OAuth2:Class
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-oauth2-1.1.2/lib/omniauth/strategies/oauth2.rb:19:in `<class:OAuth2>'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-oauth2-1.1.2/lib/omniauth/strategies/oauth2.rb:16:in `<module:Strategies>'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-oauth2-1.1.2/lib/omniauth/strategies/oauth2.rb:10:in `<module:OmniAuth>'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-oauth2-1.1.2/lib/omniauth/strategies/oauth2.rb:9:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-facebook-1.6.0/lib/omniauth/strategies/facebook.rb:1:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-facebook-1.6.0/lib/omniauth/facebook.rb:2:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/rof/cache/bundler/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/rof/cache/bundler/ruby/2.3.0/gems/omniauth-facebook-1.6.0/lib/omniauth-facebook.rb:1:in `<top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `each'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `block in require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `each'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `require'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler.rb:108:in `require'
/home/rof/src/github.com/BEWE/ROIALTY/config/application.rb:14:in `<top (required)>'
/home/rof/src/github.com/BEWE/ROIALTY/Rakefile:4:in `require'
/home/rof/src/github.com/BEWE/ROIALTY/Rakefile:4:in `<top (required)>'
/home/rof/cache/bundler/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:74:in `load'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:27:in `run'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli.rb:360:in `exec'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli.rb:20:in `dispatch'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/cli.rb:10:in `start'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/exe/bundle:35:in `block in <top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/rof/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.0/exe/bundle:27:in `<top (required)>'
/home/rof/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `load'
/home/rof/.rvm/gems/ruby-2.3.1/bin/bundle:23:in `<main>'
/home/rof/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/rof/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by parthibeyond** [comment]
I'm also facing the same issue in Travis. Has anybody solved it?

**Comment by giamma13** [comment]
if anybody has a workaround, that would be awesome

all of our CI build on codeship are not failing, even on older version of our code
so its a changes outside of our control

**Comment by darthwiz** [comment]
@parthibeyond We solved our problem by removing `oa-openid` which depended on a _very_ old version of `oa-core` (0.3.2), which was apparently being monkey-patched over the newer version of `omniauth`. Just in case, check if you have a `oa-core` dependency somewhere, I think it's what caused our trouble.

**Comment by jackkinsella** [comment]
I had the same issue but solved it by changing the order of the oa gems in the Gemfile such that the omniauth-facebook gem was placed last.
