### ISSUE TITLE
Require omniauth gem

### ISSUE THREAD

**Issue by sushant12** [mkdynamic/omniauth-facebook#282]
Is it required to use the omniauth gem if i am using omniauth-facebook in the gem file? 

what`s the diffrence betweeen these

#Gemfile
```
gem 'omniauth'

gem 'omniauth-facebook'
```

and

#Gemfile
```
gem 'omniauth-facebook'
```

**Comment by simi** [comment]
`omniauth` is indirect dependency for `omniauth-facebook`. You can use own gemfile entry for `omniauth`, if you want to specify version.
