### ISSUE TITLE
Hello, we would like to help.

### ISSUE THREAD

**Issue by Schweigert** [mkdynamic/omniauth-facebook#290]
Hello,

I'm Software Engineer at @magrathealabs. We use this gem in some of our products, and we're having security issues with it's current state. We are interested in keeping the gem development and mantainance active. If there is any chance you add us as team members in the project and on rubygems.org would be helpful. We could scheduled a call/hangouts if you have any question to us.

**Comment by abhinaykumar** [comment]
I would love to help in maintaining this gem, Although I am not that good but I can certainly try. @mkdynamic

**Comment by simi** [comment]
Hello @Schweigert, @alfakini and @abhinaykumar. Thanks for your interest. Please feel free to help with current issues and pull requests. Also from time to time testing is needed. I'll ping you before next release so we can co-operate on that together.

@Schweigert feel free to ping me separately in private to my private email on GH profile with security issues or if you think it is not sensitive, feel free to open issue/PR describing your security problems.
