### ISSUE TITLE
What version of Facebook graph API is used in the 4.0.0 version of the gem?

### ISSUE THREAD

**Issue by augnustin** [mkdynamic/omniauth-facebook#295]
I have a message in developer.facebook.com saying that I need to upgrade from 2.5 to 2.12. 

![image](https://user-images.githubusercontent.com/1970156/37392744-5397a38c-276f-11e8-9383-c714cbbd2b0b.png)

Here are the affected calls:

![image](https://user-images.githubusercontent.com/1970156/37392674-1d76bb58-276f-11e8-8bdc-07669efc4961.png)

Anyone knows what version of the FB graph the current omniauth-facebook gem version is compliant to?

Using the latest one I reckon:

```
    omniauth (1.6.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-facebook (4.0.0)
      omniauth-oauth2 (~> 1.2)
```

Cheers!

**Comment by gaborszakacs** [comment]
This gem uses the 2.6 Graph API, but I got the same warning about 2.5 too, which is a bit strange.

https://github.com/mkdynamic/omniauth-facebook/blob/0035616e16d1a78c5bc17b459214a2ab731da0aa/lib/omniauth/strategies/facebook.rb#L15

2.6 is available only until July 13, 2018, so you need to upgrade in the near future anyway. There are PRs addressing this very issue (e.g. https://github.com/mkdynamic/omniauth-facebook/pull/297), you might want to use this forked version if it doesn't get merged.

**Comment by simi** [comment]
The current version is written in readme. Also you can use custom version as described in README - https://github.com/mkdynamic/omniauth-facebook#api-version.
