### ISSUE TITLE
How to save an avatar with Active Storage

### ISSUE THREAD

**Issue by alexeyshchepin** [mkdynamic/omniauth-facebook#305]
Hey folks!
Can anybody advise me how to save an avatar from facebook to Active Storage?

I've tried those two ways. But none of them works
```ruby
user.avatar = auth.info.image
# neither
downloaded_image = open(auth.info.image)
user.avatar.attach(io: downloaded_image, filename: 'avatar.jpg', content_type: 'image/jpg')
```

Thank you!

**Comment by simi** [comment]
Hello @alexeyshchepin. Please can you open question on StackOverflow or different platform? This tracker is used only for opening issues related to `omniauth-facebook`.

This question is about active storage and not related to this issue tracker.

**Comment by alexeyshchepin** [comment]
Hi @simi! Sure, my fault.
