### ISSUE TITLE
Cannot override devise action inside omniauth controller

### ISSUE THREAD

**Issue by modusss** [mkdynamic/omniauth-facebook#306]
Hi,

My problem is that I have facebook login and normal devise login going well until I realized that the facebook user cannot edit their account without typing his password (the standard devise configuration), which it is impossible since you don't have it. For this you need to take control of the hidden action 'update' by yourself and make a customized with the differentiation between the two login's, but I coudn't do it inside the file '**controllers/omniauth_callback_controller.rb**'.

I posted this problem on [stackoverflow ](https://stackoverflow.com/questions/51634180/overriding-devise-update-action-inside-omniauth-callbacks-controller) and my code is practically the same as [this tutoriual](https://medium.com/@chinnatiptaemkaeo/integrate-omniauth-facebook-to-rails-5-1389d760d92a).

**Comment by yuvi17** [comment]
@modusss Hey, if the accepted answer from SO solved it, can we close this issue. cc: @simi
