### ISSUE TITLE
uthentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

### ISSUE THREAD

**Issue by mr3abd** [mkdynamic/omniauth-facebook#316]
when try Login with fb see that in log 
uthentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

**Comment by keviinlouis** [comment]
Any suggestions @mr3abd ?

**Comment by swiknaba** [comment]
Seems like you are using omniauth 2.
