### ISSUE TITLE
Authentication failure! invalid_credentials: OAuth2::Error, :  {"error":{"message":"Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings."

### ISSUE THREAD

**Issue by mr3abd** [mkdynamic/omniauth-facebook#317]
Hello when try login with fb can't login and when check logs see that issue 

```
Callback phase initiated.
E, [2019-02-18T14:03:08.657517 #4677] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, : 
{"error":{"message":"Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.","type":"OAuthException","code":191,"fbtrace_id":"FP3OnaueY8Y"}}
[24660a7b-e0b3-4b91-8034-e9df2309e550]   
[24660a7b-e0b3-4b91-8034-e9df2309e550] NameError (uninitialized constant OmniauthCallbacksController):

```

**Comment by artyomlagun** [comment]
Hi
The error informs you, what should you do: `To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.`.
Please, check your App Domains in FB APP settings. maybe you tried login on URL, that didn't include in App Do.

Hope it will be helpful

**Comment by simi** [comment]
I'm closing this issue for now. Please fix your app config @mr3abd and feel free to reopen this issue if you have still troubles.

**Comment by mr3abd** [comment]
Thanks all , 
But all solutions not for my case 

when put that in production file my problem is fixed 

`OmniAuth.config.full_host = "https://example.com"
production.rb`
