### ISSUE TITLE
Interested in being a maintainer

### ISSUE THREAD

**Issue by yuvi17** [mkdynamic/omniauth-facebook#322]
Hi, I would be interested in being a maintainer of this repository. Please tell me the further steps for the same. I would in the meantime go through the code and the issues section to see where I can contribute.

**Comment by simi** [comment]
Hello. I'm the only active maintainer now AFAIK. If you would like to help, feel free to browse thru issues and try to help. I think there's a lot of issues which can be already closed now. Just leave a note in any of those and I'll take a look. You can start from the oldest ones. That help will be really valuable. Thanks for your offer to help @yuvi17!

Can we close this issue for now?
